# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nokia_rib_api_pb2 as nokia__rib__api__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nokia_rib_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RibApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Modify = channel.stream_stream(
                '/Nokia.SROS.RibApi/Modify',
                request_serializer=nokia__rib__api__pb2.ModifyRequest.SerializeToString,
                response_deserializer=nokia__rib__api__pb2.ModifyResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/Nokia.SROS.RibApi/GetVersion',
                request_serializer=nokia__rib__api__pb2.VersionRequest.SerializeToString,
                response_deserializer=nokia__rib__api__pb2.VersionResponse.FromString,
                _registered_method=True)


class RibApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Modify(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RibApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Modify': grpc.stream_stream_rpc_method_handler(
                    servicer.Modify,
                    request_deserializer=nokia__rib__api__pb2.ModifyRequest.FromString,
                    response_serializer=nokia__rib__api__pb2.ModifyResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=nokia__rib__api__pb2.VersionRequest.FromString,
                    response_serializer=nokia__rib__api__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Nokia.SROS.RibApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Nokia.SROS.RibApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RibApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Modify(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/Nokia.SROS.RibApi/Modify',
            nokia__rib__api__pb2.ModifyRequest.SerializeToString,
            nokia__rib__api__pb2.ModifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Nokia.SROS.RibApi/GetVersion',
            nokia__rib__api__pb2.VersionRequest.SerializeToString,
            nokia__rib__api__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
